name: Release Lib

on:
  push:
    branches:
        - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Determine version
        run: |
          VERSION=$(node -p "require('./version_util').getVersion()")
          echo "Version: $VERSION"
          echo "::set-env name=VERSION::$VERSION"

      - name: Publish to npm
        run: |
          echo "Publishing version $VERSION to npm"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm publish
      
      - name: Create Git tag
        if: success()
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag -a "v$VERSION" -m "Release $VERSION"
          git push origin "v$VERSION"