name: Release Lib

on:
  push:
    branches:
        - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Determine version
        id: version
        run: |
          echo "::set-output name=version::$(node -p "require('./src/version_util').getVersion()")"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing version ${{ steps.version.outputs.version }} to npm"
          npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
          npm publish
      

      - name: Create Git tag
        env:
          AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          VERSION=$(node -p "require('./package.json').version")
          git tag -a "v$VERSION" -m "Release $VERSION"
          git push origin "v$VERSION" -u $AUTH_TOKEN
