name: Release Lib

on:
  push:
    branches:
        - main
    paths:
      - 'package.json'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Build library with webpack
        run: webpack --config webpack.config.js

      - name: Determine version
        id: version
        run: |
          VERSION=$(node -p "require('./src/version_util').getVersion()")
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV 

      - name: Get version from environment
        run: |
          echo "Version: ${{ env.VERSION }}"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing version ${{ env.VERSION }} to npm"
          npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
          npm publish

      - name: Create Git tag
        env:
          AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          VERSION=$(node -p "require('./package.json').version")
          git tag "v$VERSION"
          git push origin main --follow-tags
