name: Release Lib

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - 'package.json'

jobs:
  build-and-publish:
    if: |
      github.event_name == 'push' &&
      github.ref_type == 'tag' &&
      github.ref =~ '^refs/tags/v[0-9]+.[0-9]+.[0-9]+$' &&
      contains(github.event.head_commit.modified, 'package.json')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          
          
      - name: Parse version info from tag
        run: |
          # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
          VERSION=${GITHUB_REF:11}
          MAJOR=`echo "$VERSION" | cut -d . -f 1`
          MINOR=`echo "$VERSION" | cut -d . -f 2`
          PATCH=`echo "$VERSION" | cut -d . -f 3`
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Determine version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV 

      - name: Get version from environment
        run: |
          echo "Version: ${{ env.VERSION }}"

      - name: Build library
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          npm install 
          webpack --config webpack.config.js

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing version ${{ env.VERSION }} to npm"
          npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
          npm publish
          
